package com.demmers.behgameon.util;

import com.demmers.behgameon.BehgameonMod;

import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class Register {

	@SubscribeEvent
	public static void registerItems(final RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(

				BehgameonItems.accessory_1 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_1")),
				BehgameonItems.accessory_2 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_2")),
				BehgameonItems.accessory_3 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_3")),
				BehgameonItems.accessory_4 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_4")),
				BehgameonItems.accessory_5 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_5")),
				BehgameonItems.accessory_6 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_6")),
				BehgameonItems.accessory_7 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_7")),
				BehgameonItems.accessory_8 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_8")),
				BehgameonItems.accessory_9 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_9")),
				BehgameonItems.accessory_10 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_10")),
				BehgameonItems.accessory_11 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_11")),
				BehgameonItems.accessory_12 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_12")),
				BehgameonItems.accessory_13 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_13")),
				BehgameonItems.accessory_14 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_14")),
				BehgameonItems.accessory_15 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_15")),
				BehgameonItems.accessory_16 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_16")),
				BehgameonItems.accessory_17 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_17")),
				BehgameonItems.accessory_18 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_18")),
				BehgameonItems.accessory_19 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_19")),
				BehgameonItems.accessory_20 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_20")),
				BehgameonItems.accessory_21 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_21")),
				BehgameonItems.accessory_22 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_22")),
				BehgameonItems.accessory_23 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_23")),
				BehgameonItems.accessory_24 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_24")),
				BehgameonItems.accessory_25 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_25")),
				BehgameonItems.accessory_26 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_26")),
				BehgameonItems.accessory_27 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_27")),
				BehgameonItems.accessory_28 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_28")),
				BehgameonItems.accessory_29 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_29")),
				BehgameonItems.accessory_30 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_30")),
				BehgameonItems.accessory_31 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_31")),
				BehgameonItems.accessory_32 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_32")),
				BehgameonItems.accessory_33 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_33")),
				BehgameonItems.accessory_34 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_34")),
				BehgameonItems.accessory_35 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_35")),
				BehgameonItems.accessory_36 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_36")),
				BehgameonItems.accessory_37 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_37")),
				BehgameonItems.accessory_38 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_38")),
				BehgameonItems.accessory_39 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_39")),
				BehgameonItems.accessory_40 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_40")),
				BehgameonItems.accessory_41 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_41")),
				BehgameonItems.accessory_42 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_42")),
				BehgameonItems.accessory_43 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_43")),
				BehgameonItems.accessory_44 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_44")),
				BehgameonItems.accessory_45 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_45")),
				BehgameonItems.accessory_46 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_46")),
				BehgameonItems.accessory_47 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_47")),
				BehgameonItems.accessory_48 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_48")),
				BehgameonItems.accessory_49 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_49")),
				BehgameonItems.accessory_50 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_50")),
				BehgameonItems.accessory_51 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_51")),
				BehgameonItems.accessory_52 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_52")),
				BehgameonItems.accessory_53 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_53")),
				BehgameonItems.accessory_54 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_54")),
				BehgameonItems.accessory_55 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_55")),
				BehgameonItems.accessory_56 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("accessory_56")),

				BehgameonItems.ring_1 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_1")),
				BehgameonItems.ring_2 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_2")),
				BehgameonItems.ring_3 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_3")),
				BehgameonItems.ring_4 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_4")),
				BehgameonItems.ring_5 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_5")),
				BehgameonItems.ring_6 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_6")),
				BehgameonItems.ring_7 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_7")),
				BehgameonItems.ring_8 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_8")),
				BehgameonItems.ring_9 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_9")),
				BehgameonItems.ring_10 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_10")),
				BehgameonItems.ring_11 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_11")),
				BehgameonItems.ring_12 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_12")),
				BehgameonItems.ring_13 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_13")),
				BehgameonItems.ring_14 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_14")),
				BehgameonItems.ring_15 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_15")),
				BehgameonItems.ring_16 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_16")),
				BehgameonItems.ring_17 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_17")),
				BehgameonItems.ring_18 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_18")),
				BehgameonItems.ring_19 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_19")),
				BehgameonItems.ring_20 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_20")),
				BehgameonItems.ring_21 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_21")),
				BehgameonItems.ring_22 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_22")),
				BehgameonItems.ring_23 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_23")),
				BehgameonItems.ring_24 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_24")),
				BehgameonItems.ring_25 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_25")),
				BehgameonItems.ring_26 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_26")),
				BehgameonItems.ring_27 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_27")),
				BehgameonItems.ring_28 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_28")),
				BehgameonItems.ring_29 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_29")),
				BehgameonItems.ring_30 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_30")),
				BehgameonItems.ring_31 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_31")),
				BehgameonItems.ring_32 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_32")),
				BehgameonItems.ring_33 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_33")),
				BehgameonItems.ring_34 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_34")),
				BehgameonItems.ring_35 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_35")),
				BehgameonItems.ring_36 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_36")),
				BehgameonItems.ring_37 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_37")),
				BehgameonItems.ring_38 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_38")),
				BehgameonItems.ring_39 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_39")),
				BehgameonItems.ring_40 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_40")),
				BehgameonItems.ring_41 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_41")),
				BehgameonItems.ring_42 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_42")),
				BehgameonItems.ring_43 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_43")),
				BehgameonItems.ring_44 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_44")),
				BehgameonItems.ring_45 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_45")),
				BehgameonItems.ring_46 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_46")),
				BehgameonItems.ring_47 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_47")),
				BehgameonItems.ring_48 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_48")),
				BehgameonItems.ring_49 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_49")),
				BehgameonItems.ring_50 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_50")),
				BehgameonItems.ring_51 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_51")),
				BehgameonItems.ring_52 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_52")),
				BehgameonItems.ring_53 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_53")),
				BehgameonItems.ring_54 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_54")),
				BehgameonItems.ring_55 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_55")),
				BehgameonItems.ring_56 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_56")),
				BehgameonItems.ring_57 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_57")),
				BehgameonItems.ring_58 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_58")),
				BehgameonItems.ring_59 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_59")),
				BehgameonItems.ring_60 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_60")),
				BehgameonItems.ring_61 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_61")),
				BehgameonItems.ring_62 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_62")),
				BehgameonItems.ring_63 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_63")),
				BehgameonItems.ring_64 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_64")),
				BehgameonItems.ring_65 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_65")),
				BehgameonItems.ring_66 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_66")),
				BehgameonItems.ring_67 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_67")),
				BehgameonItems.ring_68 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_68")),
				BehgameonItems.ring_69 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_69")),
				BehgameonItems.ring_70 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_70")),
				BehgameonItems.ring_71 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_71")),
				BehgameonItems.ring_72 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_72")),
				BehgameonItems.ring_73 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_73")),
				BehgameonItems.ring_74 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_74")),
				BehgameonItems.ring_75 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_75")),
				BehgameonItems.ring_76 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_76")),
				BehgameonItems.ring_77 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_77")),
				BehgameonItems.ring_78 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_78")),
				BehgameonItems.ring_79 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_79")),
				BehgameonItems.ring_80 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_80")),
				BehgameonItems.ring_81 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_81")),
				BehgameonItems.ring_82 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_82")),
				BehgameonItems.ring_83 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_83")),
				BehgameonItems.ring_84 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_84")),
				BehgameonItems.ring_85 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_85")),
				BehgameonItems.ring_86 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_86")),
				BehgameonItems.ring_87 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_87")),
				BehgameonItems.ring_88 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_88")),
				BehgameonItems.ring_89 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_89")),
				BehgameonItems.ring_90 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_90")),
				BehgameonItems.ring_91 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_91")),
				BehgameonItems.ring_92 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_92")),
				BehgameonItems.ring_93 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_93")),
				BehgameonItems.ring_94 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_94")),
				BehgameonItems.ring_95 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_95")),
				BehgameonItems.ring_96 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_96")),
				BehgameonItems.ring_97 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_97")),
				BehgameonItems.ring_98 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_98")),
				BehgameonItems.ring_99 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_99")),
				BehgameonItems.ring_100 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_100")),
				BehgameonItems.ring_101 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_101")),
				BehgameonItems.ring_102 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_102")),
				BehgameonItems.ring_103 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_103")),
				BehgameonItems.ring_104 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_104")),
				BehgameonItems.ring_105 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_105")),
				BehgameonItems.ring_106 = new Item(new Item.Properties().group(BehgameonTabs.TabItemGroup)).setRegistryName(location("ring_106"))

		);
		BehgameonMod.LOGGER.info("All Items registered.");
	}

	public static ResourceLocation location(String name) {
		return new ResourceLocation(BehgameonMod.MODID, name);
	}
}