package com.deemers.behgameontweaks.init;

import java.util.ArrayList;
import java.util.List;

import com.deemers.behgameontweaks.items.BaublesNecklaceItem;
import com.deemers.behgameontweaks.items.BaublesRingItem;
import com.deemers.behgameontweaks.BehgameonTweaks;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.NonNullList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.event.RegistryEvent.Register;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import net.minecraftforge.registries.IForgeRegistry;

@ObjectHolder(BehgameonTweaks.MODID)
public final class ModItems {
	public static final Item ACCESSORY_1 = null;
    public static final Item ACCESSORY_2 = null;
    public static final Item ACCESSORY_3 = null;
  	public static final Item ACCESSORY_4 = null;
  	public static final Item ACCESSORY_5 = null;
  	public static final Item ACCESSORY_6 = null;
  	public static final Item ACCESSORY_7 = null;
  	public static final Item ACCESSORY_8 = null;
  	public static final Item ACCESSORY_9 = null;
  	public static final Item ACCESSORY_10 = null;
  	public static final Item ACCESSORY_11 = null;
  	public static final Item ACCESSORY_12 = null;
  	public static final Item ACCESSORY_13 = null;
  	public static final Item ACCESSORY_14 = null;
  	public static final Item ACCESSORY_15 = null;
  	public static final Item ACCESSORY_16 = null;
  	public static final Item ACCESSORY_17 = null;
  	public static final Item ACCESSORY_18 = null;
  	public static final Item ACCESSORY_19 = null;
  	public static final Item ACCESSORY_20 = null;
  	public static final Item ACCESSORY_21 = null;
  	public static final Item ACCESSORY_22 = null;
  	public static final Item ACCESSORY_23 = null;
  	public static final Item ACCESSORY_24 = null;
  	public static final Item ACCESSORY_25 = null;
  	public static final Item ACCESSORY_26 = null;
  	public static final Item ACCESSORY_27 = null;
  	public static final Item ACCESSORY_28 = null;
  	public static final Item ACCESSORY_29 = null;
  	public static final Item ACCESSORY_30 = null;
  	public static final Item ACCESSORY_31 = null;
  	public static final Item ACCESSORY_32 = null;
  	public static final Item ACCESSORY_33 = null;
  	public static final Item ACCESSORY_34 = null;
  	public static final Item ACCESSORY_35 = null;
  	public static final Item ACCESSORY_36 = null;
  	public static final Item ACCESSORY_37 = null;
  	public static final Item ACCESSORY_38 = null;
  	public static final Item ACCESSORY_39 = null;
  	public static final Item ACCESSORY_40 = null;
  	public static final Item ACCESSORY_41 = null;
  	public static final Item ACCESSORY_42 = null;
  	public static final Item ACCESSORY_43 = null;
  	public static final Item ACCESSORY_44 = null;
  	public static final Item ACCESSORY_45 = null;
  	public static final Item ACCESSORY_46 = null;
  	public static final Item ACCESSORY_47 = null;
  	public static final Item ACCESSORY_48 = null;
  	public static final Item ACCESSORY_49 = null;
  	public static final Item ACCESSORY_50 = null;
  	public static final Item ACCESSORY_51 = null;
  	public static final Item ACCESSORY_52 = null;
  	public static final Item ACCESSORY_53 = null;
  	public static final Item ACCESSORY_54 = null;
  	public static final Item ACCESSORY_55 = null;
  	public static final Item ACCESSORY_56 = null;
  	
  	public static final Item RING_01 = null;
  	public static final Item RING_02 = null;
  	public static final Item RING_03 = null;
  	public static final Item RING_04 = null;
  	public static final Item RING_05 = null;
  	public static final Item RING_06 = null;
  	public static final Item RING_07 = null;
  	public static final Item RING_08 = null;
  	public static final Item RING_09 = null;
  	public static final Item RING_10 = null;
  	public static final Item RING_11 = null;
  	public static final Item RING_12 = null;
  	public static final Item RING_13 = null;
  	public static final Item RING_14 = null;
  	public static final Item RING_15 = null;
  	public static final Item RING_16 = null;
  	public static final Item RING_17 = null;
  	public static final Item RING_18 = null;
  	public static final Item RING_19 = null;
  	public static final Item RING_20 = null;
  	public static final Item RING_21 = null;
  	public static final Item RING_22 = null;
  	public static final Item RING_23 = null;
  	public static final Item RING_24 = null;
  	public static final Item RING_25 = null;
  	public static final Item RING_26 = null;
  	public static final Item RING_27 = null;
  	public static final Item RING_28 = null;
  	public static final Item RING_29 = null;
  	public static final Item RING_30 = null;
  	public static final Item RING_31 = null;
  	public static final Item RING_32 = null;
  	public static final Item RING_33 = null;
  	public static final Item RING_34 = null;
  	public static final Item RING_35 = null;
  	public static final Item RING_36 = null;
  	public static final Item RING_37 = null;
  	public static final Item RING_38 = null;
  	public static final Item RING_39 = null;
  	public static final Item RING_40 = null;
  	public static final Item RING_41 = null;
  	public static final Item RING_42 = null;
  	public static final Item RING_43 = null;
  	public static final Item RING_44 = null;
  	public static final Item RING_45 = null;
  	public static final Item RING_46 = null;
  	public static final Item RING_47 = null;
  	public static final Item RING_48 = null;
  	public static final Item RING_49 = null;
  	public static final Item RING_50 = null;
  	public static final Item RING_51 = null;
  	public static final Item RING_52 = null;
  	public static final Item RING_53 = null;
  	public static final Item RING_54 = null;
  	public static final Item RING_55 = null;
  	public static final Item RING_56 = null;
  	public static final Item RING_57 = null;
  	public static final Item RING_58 = null;
  	public static final Item RING_59 = null;
  	public static final Item RING_60 = null;
  	public static final Item RING_61 = null;
  	public static final Item RING_62 = null;
  	public static final Item RING_63 = null;
  	public static final Item RING_64 = null;
  	public static final Item RING_65 = null;
  	public static final Item RING_66 = null;
  	public static final Item RING_67 = null;
  	public static final Item RING_68 = null;
  	public static final Item RING_69 = null;
  	public static final Item RING_70 = null;
  	public static final Item RING_71 = null;
  	public static final Item RING_72 = null;
  	public static final Item RING_73 = null;
  	public static final Item RING_74 = null;
  	public static final Item RING_75 = null;
  	public static final Item RING_76 = null;
  	public static final Item RING_77 = null;
  	public static final Item RING_78 = null;
  	public static final Item RING_79 = null;
  	public static final Item RING_80 = null;
  	public static final Item RING_81 = null;
  	public static final Item RING_82 = null;
  	public static final Item RING_83 = null;
  	public static final Item RING_84 = null;
  	public static final Item RING_85 = null;
  	public static final Item RING_86 = null;
  	public static final Item RING_87 = null;
  	public static final Item RING_88 = null;
  	public static final Item RING_89 = null;
  	public static final Item RING_90 = null;
  	public static final Item RING_91 = null;
  	public static final Item RING_92 = null;
  	public static final Item RING_93 = null;
  	public static final Item RING_94 = null;
  	public static final Item RING_95 = null;
  	public static final Item RING_96 = null;
  	public static final Item RING_97 = null;
  	public static final Item RING_98 = null;
  	public static final Item RING_99 = null;
  	public static final Item RING_100 = null;
  	public static final Item RING_101 = null;
  	public static final Item RING_102 = null;
  	public static final Item RING_103 = null;
  	public static final Item RING_104 = null;
  	public static final Item RING_105 = null;
  	public static final Item RING_106 = null;
    
    public static Item[] itemList;
	public static NonNullList<ItemStack> variantList;
	static {
		List<Item> items = new ArrayList<Item>();
		for (int i = 1; i <= 56; i++)
			items.add(new BaublesNecklaceItem("accessory_" + i));
		BehgameonTweaks.LOGGER.info("Registered accessories");
		for (int i = 1; i <= 106; i++)
			items.add(new BaublesRingItem("ring_" + i));
		BehgameonTweaks.LOGGER.info("Registered rings");
		itemList = items.toArray(new Item[items.size()]);
	}

}